image:
  repository: ghcr.io/akarsh5080/service-nginx-repo
  tag: 96e9254e6cd0a8d3e26b33e4f1d72c16e21c4ca2

persistence:
  enabled: false
  size: 1Gi

replicaCount: 1

service:
  type: NodePort
  port: 80
