apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-repo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/<your-org>/gitops-repo
    targetRevision: HEAD

    # 🔥 THIS IS KEY
    path: charts/microservice

    helm:
      valueFiles:
        - ../../environments/dev/apps/app-repo/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
