apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-repo
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/akarsh5080/gitops-repo.git
    targetRevision: HEAD
    path: environments/dev/apps/app-repo
    helm:
      valueFiles:
        - ../../apps/app-repo/dev/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
