apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.0

    helm:   # ✅ CORRECT PLACE
      values: |
        auth:
          username: admin
          password: admin123
          database: mydb
        primary:
          persistence:
            enabled: true
            size: 1Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
