image:
  repository: ghcr.io/akarsh5080/app-repo
  tag: c62c2c4d162f72a880454e85582f7d3a4aa7cd84

persistence:
  enabled: false
  size: 1Gi

replicaCount: 2

service:
  type: NodePort
  port: 80

statefulset:
  enabled: false
